apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastzero
  namespace: fastzero-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastzero
  template:
    metadata:
      labels:
        app: fastzero
    spec:
      containers:
      - name: fastzero
        image: jlxdocky/fastzero:latest
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: fastzero
  namespace: fastzero-app
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8000
  selector:
    app: fastzero
